/**
 * Curated icon sets for committees and parliamentary groups.
 *
 * A closed list rather than free text on purpose. The whole `lucide` collection
 * is bundled on the server with `fallbackToApi: false`, so an unknown name does
 * not error: it renders nothing at all. A list turns a typo into a 400.
 *
 * Names are stored without the `i-lucide-` prefix; `iconName` puts it back.
 */
export const COMMITTEE_ICONS = [
  // Institutions and law
  'landmark',
  'building-2',
  'building',
  'library',
  'scale',
  'gavel',
  'scroll',
  'scroll-text',
  'file-text',
  'clipboard-list',
  'vote',
  'shield',
  'shield-check',
  'lock',
  'swords',
  'handshake',
  'heart-handshake',
  'users',
  'user-check',
  'globe',
  'earth',
  'map',
  'languages',
  // Economy and work
  'briefcase',
  'banknote',
  'coins',
  'piggy-bank',
  'trending-up',
  'store',
  'warehouse',
  'factory',
  'hard-hat',
  'wrench',
  'truck',
  'bus',
  'train-front',
  'plane',
  'ship',
  'sailboat',
  // Land, food and environment
  'tractor',
  'wheat',
  'fish',
  'utensils',
  'leaf',
  'trees',
  'sprout',
  'droplets',
  'recycle',
  'wind',
  'sun',
  'flame',
  'fuel',
  'zap',
  'thermometer',
  'mountain-snow',
  'waves',
  // People, health and rights
  'heart-pulse',
  'stethoscope',
  'pill',
  'baby',
  'accessibility',
  'hand-heart',
  'equal',
  'house',
  // Knowledge, science and culture
  'graduation-cap',
  'school',
  'book-open',
  'flask-conical',
  'microscope',
  'atom',
  'rocket',
  'satellite',
  'cpu',
  'network',
  'wifi',
  'bug',
  'lightbulb',
  'ruler',
  // Media and the arts
  'radio',
  'tv',
  'newspaper',
  'megaphone',
  'mic',
  'music',
  'film',
  'camera',
  'theater',
  'palette',
  'hammer',
] as const

export const GROUP_ICONS = [
  // Flags and emblems
  'flag',
  'star',
  'sparkles',
  'crown',
  'shield',
  'award',
  'medal',
  'trophy',
  'gem',
  'key',
  // Nature
  'sun',
  'sunrise',
  'sunset',
  'moon',
  'cloud',
  'wind',
  'snowflake',
  'flame',
  'droplet',
  'waves',
  'leaf',
  'sprout',
  'clover',
  'tree-pine',
  'trees',
  'wheat',
  'rose',
  'citrus',
  'apple',
  'grape',
  'carrot',
  'mountain',
  'shell',
  // Animals
  'bird',
  'feather',
  'fish',
  'cat',
  'dog',
  'rabbit',
  'squirrel',
  'turtle',
  'paw-print',
  // Work and tools
  'hammer',
  'anvil',
  'pickaxe',
  'wrench',
  'scissors',
  'axe',
  'scale',
  'handshake',
  'users',
  'heart',
  'hand-heart',
  // Movement and ideas
  'compass',
  'anchor',
  'sailboat',
  'ship',
  'rocket',
  'orbit',
  'atom',
  'zap',
  'lightbulb',
  'megaphone',
  'music',
  'palette',
  'puzzle',
  'umbrella',
  'tent',
  'infinity',
  // Plain shapes, for a group that wants none of the above
  'circle-dot',
  'triangle',
  'square',
  'diamond',
  'pentagon',
  'hexagon',
  'octagon',
  'asterisk',
] as const

export type CommitteeIcon = (typeof COMMITTEE_ICONS)[number]
export type GroupIcon = (typeof GROUP_ICONS)[number]

/** Used when nothing is chosen, and for the plenary, which has no row to store one on. */
export const DEFAULT_COMMITTEE_ICON: CommitteeIcon = 'landmark'
export const DEFAULT_GROUP_ICON: GroupIcon = 'flag'
export const PLENARY_ICON = 'star'

export function iconName(name: string | null | undefined, fallback: string) {
  return `i-lucide-${name || fallback}`
}
